### Numpy Library

- Processing N - Dimensional arrays

In [7]:
import numpy as np

li = [1,2,3,'z']

a = np.array(li)
#type(a)
#a

b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
rn = np.random.randint(0,100,size = 10)
rn

array([29, 21,  3, 50, 70, 12, 46, 64, 49, 78])

In [27]:
## 3 - dimensional matrix 

m3 = np.random.randint(0,2,size=(3,3,3,4))
m3[2][2][2][1]

1

In [38]:
m3.ndim
#m3.size
#m3.shape
#m3.dtype
#m3.itemsize
#m3.nbytes

4

In [33]:
rn[-5:]

array([12, 46, 64, 49, 78])

In [39]:
m3[:2, :3]

array([[[[1, 0, 0, 0],
         [0, 0, 1, 0],
         [1, 0, 0, 1]],

        [[0, 1, 0, 1],
         [1, 0, 1, 0],
         [1, 1, 1, 1]],

        [[1, 1, 0, 0],
         [1, 1, 0, 0],
         [1, 1, 1, 1]]],


       [[[0, 0, 1, 0],
         [1, 0, 0, 0],
         [1, 0, 1, 1]],

        [[1, 0, 0, 0],
         [1, 0, 1, 1],
         [0, 1, 1, 0]],

        [[1, 0, 1, 0],
         [0, 0, 1, 1],
         [0, 1, 1, 0]]]])

In [40]:
m3[::-1 , ::-1]

array([[[[0, 0, 1, 0],
         [0, 0, 0, 0],
         [0, 1, 1, 0]],

        [[0, 0, 0, 1],
         [1, 1, 1, 0],
         [0, 1, 0, 0]],

        [[1, 0, 1, 1],
         [1, 0, 1, 0],
         [1, 0, 0, 1]]],


       [[[1, 0, 1, 0],
         [0, 0, 1, 1],
         [0, 1, 1, 0]],

        [[1, 0, 0, 0],
         [1, 0, 1, 1],
         [0, 1, 1, 0]],

        [[0, 0, 1, 0],
         [1, 0, 0, 0],
         [1, 0, 1, 1]]],


       [[[1, 1, 0, 0],
         [1, 1, 0, 0],
         [1, 1, 1, 1]],

        [[0, 1, 0, 1],
         [1, 0, 1, 0],
         [1, 1, 1, 1]],

        [[1, 0, 0, 0],
         [0, 0, 1, 0],
         [1, 0, 0, 1]]]])

In [41]:
m3[::-1, ::-1]

array([[[[0, 0, 1, 0],
         [0, 0, 0, 0],
         [0, 1, 1, 0]],

        [[0, 0, 0, 1],
         [1, 1, 1, 0],
         [0, 1, 0, 0]],

        [[1, 0, 1, 1],
         [1, 0, 1, 0],
         [1, 0, 0, 1]]],


       [[[1, 0, 1, 0],
         [0, 0, 1, 1],
         [0, 1, 1, 0]],

        [[1, 0, 0, 0],
         [1, 0, 1, 1],
         [0, 1, 1, 0]],

        [[0, 0, 1, 0],
         [1, 0, 0, 0],
         [1, 0, 1, 1]]],


       [[[1, 1, 0, 0],
         [1, 1, 0, 0],
         [1, 1, 1, 1]],

        [[0, 1, 0, 1],
         [1, 0, 1, 0],
         [1, 1, 1, 1]],

        [[1, 0, 0, 0],
         [0, 0, 1, 0],
         [1, 0, 0, 1]]]])

In [42]:
print(rn)

[29 21  3 50 70 12 46 64 49 78]


In [53]:
rn.reshape(5,2)

array([[29, 21],
       [ 3, 50],
       [70, 12],
       [46, 64],
       [49, 78]])

In [57]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
 #splitting of arrays

a =[1,2,3,4,5,6,7,8]
x,y,z = np.split(a,[4,3])
print(x,y,z)

[1 2 3 4] [] [4 5 6 7 8]


In [ ]:
import numpy as np
c = np.array([[1,2,3],[4,5,6],[3,5,6]])
d = np.array([[3,3,9],[4,7,8],[1,2,3]])
def get_row

In [66]:
import numpy as np
m= np.ones((3,3))
print(m,'\n')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 



In [67]:
import numpy as np
m= np.ones((3,3),dtype = int)
print(m,'\n')

[[1 1 1]
 [1 1 1]
 [1 1 1]] 



In [73]:
keyfile = 'DataFiles/key.txt'
def dictionaryKeyFile(keyfile):
    key ={}
    with open(keyfile, 'r') as f:
        for line in f:
            line = line.split()
            key[line[0]] = line[1]
    return key

dictionaryKeyFile(keyfile)


def encryptData(datafile, keyfile):
    # construct a file for keydata
    key = dictionaryKeyFile(keyfile)
    with open(datafile,'r') as f:
        filedata = f.read().split('\n')
    with open('DataFiles/encryptMarks.txt', 'w') as f:
        for mark in filedata:
            line = ''
            for n in mark:
                line += key[n]
            f.write(line+'\n')
        return
datafile ='Datafiles/marks.txt'
import timeit
st = timeit.default_timer()
encryptData(datafile,keyfile)
print(timeit.default_timer()-st)

0.010131322000233922


In [ ]:
#scipy.org

### Pandas 

Usecases
- Data Cleaning
- Data Transformation
- Data Analysis

Notations

- Series (row)
- Dataframes (table)

In [74]:
import pandas as pd

int1 = {'s1':21, 's2':18, 's3':25}
int1 = pd.Series(int1)

int1

s1    21
s2    18
s3    25
dtype: int64

In [75]:
int1 = {'s1':21, 's2':18, 's3':25}
int1 = pd.Series(int1)

int2 = {'s1':13, 's2':16, 's3':20}
int2 = pd.Series(int2)

int2

s1    13
s2    16
s3    20
dtype: int64

In [76]:
final = {'Internal1':int1,'Internal2':int2}

final=pd.DataFrame(final)
final

Internal1  Internal2
s1         21         13
s2         18         16
s3         25         20

In [77]:
final.columns

Index(['Internal1', 'Internal2'], dtype='object')

In [79]:
final.values

array([[21, 13],
       [18, 16],
       [25, 20]], dtype=int64)

In [80]:
final.values[2,0]

25

In [81]:
final.values[2]

array([25, 20], dtype=int64)

In [82]:
final.values[2][0]

25

In [84]:
for row in final.values:
    print('Internal1 -',row[0], 'Internal2 - ',row[1] )

Internal1 - 21 Internal2 -  13
Internal1 - 18 Internal2 -  16
Internal1 - 25 Internal2 -  20


In [88]:
final.loc['S4'] = [15, 18]
final

Internal1  Internal2
s1         21         13
s2         18         16
s3         25         20
S4         15         18

In [91]:
final.drop('s2')

Internal1  Internal2
s1         21         13
s3         25         20
S4         15         18

In [92]:
final

Internal1  Internal2
s1         21         13
s2         18         16
s3         25         20
S4         15         18

In [99]:
final.values[2] =[22,25]

In [100]:
final

Internal1  Internal2
s1         21         13
s3         25         20
S4         22         25

In [101]:
# Reading CSV File Data
import pandas as pd

filepath = 'DataFiles/income.csv'
incomedf = pd.read_csv(filepath)

incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [106]:
# Extarct income of all states in 2013

for row in incomedf.values:
    print(row[1],'.',row[-1])

Alabama . 41381
Alaska . 61137
Arizona . 50602
Arkansas . 39919
California . 57528


In [109]:
# Average income of a particular state

s = 0
for i in range(2,11):
    s +=incomedf.values[2][i]
    
s/len(incomedf.values[2][2:])    

47214.77777777778

In [111]:
# Average income of all states in year 2012
s = 0
for row in incomedf.values:
    s += row[-2]
    
s/len(incomedf.values)

50038.8